/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.ues.edu.vista.componentes;

import com.formdev.flatlaf.FlatDarkLaf;
import com.formdev.flatlaf.FlatLaf;
import com.formdev.flatlaf.FlatLightLaf;
import com.formdev.flatlaf.extras.FlatAnimatedLafChange;
import com.ues.edu.controlador.ControladorLogin;
import com.ues.edu.modelo.Usuario;
import com.ues.edu.vista.Dashboard;
import com.ues.edu.vista.Login;
import java.awt.Color;
import java.awt.Cursor;
import java.awt.EventQueue;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.RenderingHints;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import javax.swing.UIManager;

/**
 *
 * @author jorge
 */
public class Footer extends javax.swing.JPanel {

//    private HeaderMenuListener listener;
    /**
     * Creates new form Header
     */
    public Footer() {
        initComponents();
        setOpaque(false);
        initExitListener();
        initThemeListener();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblSalir = new javax.swing.JLabel();
        toggleTema = new com.ues.edu.vista.swing.ToggleSwitch();

        lblSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/logout1.png"))); // NOI18N
        lblSalir.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 5, 5, 5));

        toggleTema.setText("toggleSwitch1");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(toggleTema, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 488, Short.MAX_VALUE)
                .addComponent(lblSalir)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(lblSalir, javax.swing.GroupLayout.DEFAULT_SIZE, 55, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(toggleTema, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    @Override
    protected void paintComponent(Graphics g) {
        Graphics2D g2 = (Graphics2D) g;
        g2.setRenderingHint(RenderingHints.KEY_ANTIALIASING, RenderingHints.VALUE_ANTIALIAS_ON);
        g2.setColor(getBackground());
        g2.fillRoundRect(0, 0, getWidth(), getHeight(), 15, 15);
        super.paintComponent(g);
    }

    private void initThemeListener() {
        // Sincronizar estado inicial del botón con el tema actual
        if (UIManager.getLookAndFeel() instanceof FlatDarkLaf) {
            toggleTema.setSelected(false); // Modo Oscuro = Botón a la izquierda
        } else {
            toggleTema.setSelected(true);  // Modo Claro = Botón a la derecha
        }

        toggleTema.addActionListener(e -> {
            EventQueue.invokeLater(() -> {
                // Animación suave
                FlatAnimatedLafChange.showSnapshot();

                try {
                    if (toggleTema.isSelected()) {
                        // Cambiar a Claro
                        UIManager.setLookAndFeel(new FlatLightLaf());
                    } else {
                        // Cambiar a Oscuro
                        UIManager.setLookAndFeel(new FlatDarkLaf());
                    }
                } catch (Exception ex) {
                    System.err.println("Error cambiando tema: " + ex.getMessage());
                }

                // Actualiza toda la interfaz gráfica
                FlatLaf.updateUI();
                FlatAnimatedLafChange.hideSnapshotWithAnimation();
            });
        });
    }

    private void initExitListener() {
        lblSalir.addMouseListener(new MouseAdapter() {

            @Override
            public void mouseEntered(MouseEvent e) {
                lblSalir.setOpaque(true);
                lblSalir.setBackground(new Color(255, 0, 0, 100)); // Gris claro semi-transparente
                lblSalir.setCursor(new Cursor(Cursor.HAND_CURSOR));
            }

            @Override
            public void mouseExited(MouseEvent e) {
                lblSalir.setOpaque(false);
                lblSalir.setBackground(new Color(0, 0, 0, 0));
            }

            @Override
            public void mousePressed(MouseEvent e) {
                int confirmacion = javax.swing.JOptionPane.showConfirmDialog(
                        null,
                        "¿Está seguro que desea cerrar la sesión?",
                        "Cerrar Sesión",
                        javax.swing.JOptionPane.YES_NO_OPTION,
                        javax.swing.JOptionPane.QUESTION_MESSAGE
                );

                if (confirmacion == javax.swing.JOptionPane.YES_OPTION) {
                    javax.swing.JOptionPane.showMessageDialog(
                            null,
                            "¡Hasta pronto! Gracias por usar el sistema.",
                            "Saliendo",
                            javax.swing.JOptionPane.INFORMATION_MESSAGE
                    );

                    java.awt.Window parentWindow = javax.swing.SwingUtilities.getWindowAncestor(Footer.this);
                    if (parentWindow != null) {
                        parentWindow.dispose();
                    }

                    Login login = new Login();
                    ControladorLogin controlador = new ControladorLogin(login);
                    login.setVisible(true);
                }
            }
        }
        );
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblSalir;
    private com.ues.edu.vista.swing.ToggleSwitch toggleTema;
    // End of variables declaration//GEN-END:variables
}
