/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.ues.edu.vista;

import com.ues.edu.controlador.ControladorEmpleado;
import com.ues.edu.controlador.ControladorFunciones;
import com.ues.edu.controlador.ControladorMetodoPago;
import com.ues.edu.controlador.ControladorPeliculas;
import com.ues.edu.controlador.ControladorPermiso;
import com.ues.edu.controlador.ControladorPrueba;
import com.ues.edu.controlador.ControladorRol;
import com.ues.edu.controlador.ControladorSala;
import com.ues.edu.controlador.ControladorUsuario;
import com.ues.edu.interfaces.HeaderMenuListener;
import com.ues.edu.interfaces.MenuSelectionListener;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.event.ActionEvent;
import javax.swing.Timer;

/**
 *
 * @author jorge
 */
public class Dashboard extends javax.swing.JFrame implements HeaderMenuListener, MenuSelectionListener {
    
    private final int MENU_ANCHO_MAX = 215;
    private final int MENU_ANCHO_MIN = 0;
    private final int VELOCIDAD = 15;
    private final Timer animador;
    private int targetWidth;
    private boolean menuVisible = true;
    private final javax.swing.JPanel panelSecundario;
    
    public Dashboard() {
        animador = new Timer(5, (ActionEvent e) -> {
            animateMenuWidth();
        });
        initComponents();
        
        this.setLocationRelativeTo(null);
        setBackground(new Color(0, 0, 0, 0));
        setExtendedState(MAXIMIZED_BOTH);

        //--- 1. CONFIGURACIÓN DEL PANEL SECUNDARIO ---
        panelSecundario = new javax.swing.JPanel();
        panelSecundario.setLayout(new java.awt.BorderLayout());
        panelSecundario.setOpaque(false);

        //2. Montar la estructura interna de panelSecundario (Header + Vistas + Footer)
        int realHeaderAlto = header1.getPreferredSize().height;
        header1.setPreferredSize(new Dimension(0, realHeaderAlto));
        
        panelSecundario.add(header1, java.awt.BorderLayout.NORTH);
        panelSecundario.add(footer1, java.awt.BorderLayout.SOUTH);

        //3. Montar la estructura principal en 'bg'
        this.getContentPane().setLayout(new java.awt.BorderLayout());
        this.getContentPane().add(bg, java.awt.BorderLayout.CENTER);
        
        bg.setLayout(new java.awt.BorderLayout());
        menu1.setPreferredSize(new Dimension(MENU_ANCHO_MAX, 0));
        
        bg.add(menu1, java.awt.BorderLayout.WEST);          // Menú a la izquierda
        bg.add(panelSecundario, java.awt.BorderLayout.CENTER); // Contenedor Secundario al centro

        //5. Inicialización de Listeners
        header1.setMenuToggleListener(this);
        menu1.getListaMenu().setSelectionListener(this);
        
        bg.revalidate();
        this.getContentPane().revalidate();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bg = new javax.swing.JPanel();
        menu1 = new com.ues.edu.vista.componentes.Menu();
        header1 = new com.ues.edu.vista.componentes.Header();
        footer1 = new com.ues.edu.vista.componentes.Footer();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        javax.swing.GroupLayout bgLayout = new javax.swing.GroupLayout(bg);
        bg.setLayout(bgLayout);
        bgLayout.setHorizontalGroup(
            bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bgLayout.createSequentialGroup()
                .addComponent(menu1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(footer1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(bgLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(header1, javax.swing.GroupLayout.PREFERRED_SIZE, 594, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );
        bgLayout.setVerticalGroup(
            bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bgLayout.createSequentialGroup()
                .addComponent(menu1, javax.swing.GroupLayout.PREFERRED_SIZE, 533, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(bgLayout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(header1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(footer1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void showJPanel(javax.swing.JPanel p) {

        //Obtiene el LayoutManager del panel que contiene las vistas
        java.awt.BorderLayout layout = (java.awt.BorderLayout) panelSecundario.getLayout();

        //1. Encuentra el componente actual en el CENTRO
        java.awt.Component centerComponent = layout.getLayoutComponent(panelSecundario, java.awt.BorderLayout.CENTER);

        //2. Esto limpia la vista anterior
        if (centerComponent != null) {
            panelSecundario.remove(centerComponent);
        }

        //3. Añade la nueva vista SOLO si no es NULL
        if (p != null) {
            panelSecundario.add(p, java.awt.BorderLayout.CENTER);
        }

        //4. Forzar el redibujado en ambos niveles (por si acaso)
        panelSecundario.revalidate();
        panelSecundario.repaint();
        bg.revalidate(); //Revalida el padre también
    }
    
    private void animateMenuWidth() {
        int currentWidth = menu1.getPreferredSize().width;
        int newWidth = currentWidth; // Variable local

        if (currentWidth < targetWidth) {
            newWidth = Math.min(currentWidth + VELOCIDAD, targetWidth);
        } else if (currentWidth > targetWidth) {
            newWidth = Math.max(currentWidth - VELOCIDAD, targetWidth);
        }
        
        if (newWidth == targetWidth) {
            animador.stop();
        }
        
        menu1.setPreferredSize(new Dimension(newWidth, menu1.getHeight()));
        
        bg.revalidate();
        bg.repaint();
    }

    //--- IMPLEMENTACIÓN DE INTERFACES ---
    //1. HeaderMenuListener: Activa/Desactiva la animación
    @Override
    public void toggleMenuVisibility() {
        if (menuVisible) {
            targetWidth = MENU_ANCHO_MIN;
        } else {
            targetWidth = MENU_ANCHO_MAX;
        }
        menuVisible = !menuVisible;
        animador.start();
    }
    
    @Override
    public void onModuleSelected(String itemName) {
        switch (itemName) {
            
            case "Peliculas" -> {
                Mantenimiento mantto = new Mantenimiento("Peliculas");
                
                ControladorPeliculas controlador = new ControladorPeliculas(mantto); //aqui debo agregar el nuevo controlador
                showJPanel(mantto);
            }
            case "Funciones" -> {
                Mantenimiento mantto = new Mantenimiento("Funciones");
                
                ControladorFunciones controlador = new ControladorFunciones(mantto); //aqui debo agregar el nuevo controlador
                showJPanel(mantto);
            }
            case "Salas" -> {
                Mantenimiento mantto = new Mantenimiento("Salas");
                
                ControladorSala controlador = new ControladorSala(mantto); //aqui debo agregar el nuevo controlador
                showJPanel(mantto);
            }
            
            case "Prueba" -> {
                VistaPrueba vista = new VistaPrueba();
                ControladorPrueba controlador = new ControladorPrueba(vista);
                showJPanel(vista);
            }
            
            case "Empleados" -> {
                Mantenimiento mantto = new Mantenimiento("Empleados");
                ControladorEmpleado cemp = new ControladorEmpleado(mantto);
                showJPanel(mantto);
            }
            
            case "Roles" -> {
                Mantenimiento mantto = new Mantenimiento("Roles");
                ControladorRol cr = new ControladorRol(mantto);
                showJPanel(mantto);
            }
            
            case "Permisos" -> {
                Mantenimiento mantto = new Mantenimiento("Permisos");
                ControladorPermiso cnt = new ControladorPermiso(mantto);
                showJPanel(mantto);
            }
            
            case "Metodo de Pago" -> {
                Mantenimiento mantto = new Mantenimiento("Metodo de pago");
                ControladorMetodoPago cmp = new ControladorMetodoPago(mantto);
                showJPanel(mantto);
            }
            
            case "Usuarios" -> {
                Mantenimiento mantto = new Mantenimiento("Usuarios");
                ControladorUsuario cu = new ControladorUsuario(mantto);
                showJPanel(mantto);
            }
            
            case "INICIO" -> {
                showJPanel(null);
            }
            case "SALIR" -> {
                
            }
        }
    }

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bg;
    private com.ues.edu.vista.componentes.Footer footer1;
    private com.ues.edu.vista.componentes.Header header1;
    private com.ues.edu.vista.componentes.Menu menu1;
    // End of variables declaration//GEN-END:variables

}
