/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package com.ues.edu.vista;

import javax.swing.JOptionPane;

/**
 *
 * @author radon
 */
public class ModalPermisoRol extends javax.swing.JDialog {

    /**
     * Creates new form ModalPermisoRol
     */
    public ModalPermisoRol(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        
    }
    public ModalPermisoRol(java.awt.Frame parent, boolean modal, int idRol, String nombreRol) {
        super(parent, modal);
        initComponents();

        this.lbTitulo.setText("Asignar Permiso a Rol");
        this.lbRolSeleccionada.setText(nombreRol);

        cargarPermisos(); // Llenar combo
        btnGuardar.addActionListener(e -> guardarPermisoRol(idRol));
    }

    /**
     * Cargar los permisos desde la base de datos en el combo
     */
    private void cargarPermisos() {
        try {
            com.ues.edu.modelo.dao.PermisoDao pDao = new com.ues.edu.modelo.dao.PermisoDao();
            com.ues.edu.modelo.estructuras.ListaSimple<com.ues.edu.modelo.Permiso> lista = pDao.selectAll();

            cmbPermisos.removeAllItems();

            if (lista != null && !lista.isEmpty()) {
                for (com.ues.edu.modelo.Permiso permiso : lista.toArray()) {
                    cmbPermisos.addItem(permiso.getNombrePermiso());
                }
            } else {
                cmbPermisos.addItem("No hay permisos disponibles");
                cmbPermisos.setEnabled(false);
                btnGuardar.setEnabled(false);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this,
                    "Error al cargar permisos:\n" + e.getMessage(),
                    "Error", JOptionPane.ERROR_MESSAGE);
        }
    }
    private void guardarPermisoRol(int idRol) {
        String nombrePermiso = (String) cmbPermisos.getSelectedItem();

        if (nombrePermiso == null || nombrePermiso.equals("No hay permisos disponibles")) {
            JOptionPane.showMessageDialog(this,
                    "Seleccione un permiso válido.", "Aviso", JOptionPane.WARNING_MESSAGE);
            return;
        }

        try {
            com.ues.edu.modelo.dao.PermisoDao pDao = new com.ues.edu.modelo.dao.PermisoDao();
            com.ues.edu.modelo.estructuras.ListaSimple<com.ues.edu.modelo.Permiso> lista =
                    pDao.obtenerIdPorNombre(nombrePermiso);

            if (lista == null || lista.isEmpty()) {
                JOptionPane.showMessageDialog(this,
                        "No se encontró el permiso seleccionado.", "Error", JOptionPane.ERROR_MESSAGE);
                return;
            }

            int idPermiso = lista.get(0).getIdPermiso();

            com.ues.edu.modelo.dao.Conexion conexion = new com.ues.edu.modelo.dao.Conexion();
            java.sql.Connection con = conexion.getConexion();

            String sql = "INSERT INTO rol_permiso(id_rol, id_permiso) VALUES (?, ?)";
            java.sql.PreparedStatement ps = con.prepareStatement(sql);
            ps.setInt(1, idRol);
            ps.setInt(2, idPermiso);
            ps.executeUpdate();

            JOptionPane.showMessageDialog(this,
                    "Permiso asignado correctamente al rol.",
                    "Éxito", JOptionPane.INFORMATION_MESSAGE);

            this.dispose();

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this,
                    "Error al guardar permiso:\n" + e.getMessage(),
                    "Error", JOptionPane.ERROR_MESSAGE);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fondo = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        lbSala = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        btnGuardar = new javax.swing.JButton();
        lbTitulo = new javax.swing.JLabel();
        lbRolSeleccionada = new javax.swing.JLabel();
        cmbPermisos = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        lbSala.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        lbSala.setText("Rol Seleccionado");

        jLabel1.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        jLabel1.setText("Permiso");

        btnGuardar.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        btnGuardar.setText("GUARDAR");

        lbTitulo.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N

        lbRolSeleccionada.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N

        cmbPermisos.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N

        javax.swing.GroupLayout fondoLayout = new javax.swing.GroupLayout(fondo);
        fondo.setLayout(fondoLayout);
        fondoLayout.setHorizontalGroup(
            fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, fondoLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lbTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(fondoLayout.createSequentialGroup()
                .addGroup(fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(fondoLayout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(fondoLayout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnGuardar)
                            .addComponent(cmbPermisos, 0, 150, Short.MAX_VALUE)
                            .addComponent(lbSala, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbRolSeleccionada, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(59, Short.MAX_VALUE))
        );
        fondoLayout.setVerticalGroup(
            fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fondoLayout.createSequentialGroup()
                .addComponent(lbTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lbSala)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbRolSeleccionada, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cmbPermisos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnGuardar)
                .addGap(40, 40, 40))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(fondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(fondo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(ModalPermisoRol.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(ModalPermisoRol.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(ModalPermisoRol.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(ModalPermisoRol.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the dialog */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                ModalPermisoRol dialog = new ModalPermisoRol(new javax.swing.JFrame(), true);
//                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
//                    @Override
//                    public void windowClosing(java.awt.event.WindowEvent e) {
//                        System.exit(0);
//                    }
//                });
//                dialog.setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnGuardar;
    public javax.swing.JComboBox<String> cmbPermisos;
    private javax.swing.JPanel fondo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JSeparator jSeparator1;
    public javax.swing.JLabel lbRolSeleccionada;
    private javax.swing.JLabel lbSala;
    public javax.swing.JLabel lbTitulo;
    // End of variables declaration//GEN-END:variables
}
