/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.ues.edu.vista;

/**
 *
 * @author radon
 */
public class VistaPermisoRol extends javax.swing.JPanel {

     public VistaPermisoRol() {
        this("Permisos del Rol");
    }
    public VistaPermisoRol(String titulo) {
        initComponents();
        this.lblTitulo.setText(titulo);
        fondo.addMouseListener(new java.awt.event.MouseAdapter() {
            @Override
            public void mousePressed(java.awt.event.MouseEvent e) {
               
               for (java.awt.Component comp : fondo.getComponents()) {
                    if (comp instanceof javax.swing.JButton btn) {
                        btn.getModel().setArmed(false);
                        btn.setFocusable(false);
                        javax.swing.SwingUtilities.invokeLater(() -> btn.setFocusable(true));
                    }
                }
                btnCambios.setEnabled(true);
                btnAsignar.setEnabled(false);
                tbDatos.clearSelection();
                fondo.requestFocusInWindow();
            }
        });
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fondo = new javax.swing.JPanel();
        btnCambios = new javax.swing.JButton();
        btnAsignar = new javax.swing.JButton();
        lblTitulo = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbDatos = new com.ues.edu.vista.swing.TablaConCheckboxes();

        btnCambios.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        btnCambios.setText("GUARDA CAMBIOS");

        btnAsignar.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        btnAsignar.setText("ASIGNAR PERMISO");

        lblTitulo.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N

        jScrollPane1.setViewportView(tbDatos);

        javax.swing.GroupLayout fondoLayout = new javax.swing.GroupLayout(fondo);
        fondo.setLayout(fondoLayout);
        fondoLayout.setHorizontalGroup(
            fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, fondoLayout.createSequentialGroup()
                .addContainerGap(589, Short.MAX_VALUE)
                .addComponent(lblTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 380, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(fondoLayout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addComponent(btnCambios)
                .addGap(18, 18, 18)
                .addComponent(btnAsignar)
                .addContainerGap(632, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, fondoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        fondoLayout.setVerticalGroup(
            fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fondoLayout.createSequentialGroup()
                .addComponent(lblTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addGroup(fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCambios)
                    .addComponent(btnAsignar))
                .addGap(30, 30, 30)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 403, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(fondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(fondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnAsignar;
    public javax.swing.JButton btnCambios;
    private javax.swing.JPanel fondo;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JLabel lblTitulo;
    public com.ues.edu.vista.swing.TablaConCheckboxes tbDatos;
    // End of variables declaration//GEN-END:variables
}
