/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.ues.edu.vista;

import java.awt.Color;
import java.awt.GradientPaint;
import java.awt.Graphics2D;
import java.awt.RenderingHints;
import java.awt.geom.GeneralPath;
import java.awt.image.BufferedImage;
import javax.swing.ImageIcon;

/**
 *
 * @author jorge
 */
public class VistaBoletos extends javax.swing.JPanel {

    /**
     * Creates new form VistaBoletos
     *
     * @param titulo
     */
    public VistaBoletos(String titulo) {
        initComponents();
        lblTitulo.setText(titulo);
        crearEfectoPantalla(600, 50);
//        lbPantalla.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fondo = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        lblTitulo = new javax.swing.JLabel();
        panelAsientos = new javax.swing.JPanel();
        lbPantalla = new javax.swing.JLabel();
        btnSelectFuncion = new javax.swing.JButton();
        lbSala = new javax.swing.JLabel();
        btnFactura = new javax.swing.JButton();
        lbFuncion = new javax.swing.JLabel();
        lbPrecio = new javax.swing.JLabel();
        lbHorario = new javax.swing.JLabel();
        lbTotal = new javax.swing.JLabel();

        lblTitulo.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N

        javax.swing.GroupLayout panelAsientosLayout = new javax.swing.GroupLayout(panelAsientos);
        panelAsientos.setLayout(panelAsientosLayout);
        panelAsientosLayout.setHorizontalGroup(
            panelAsientosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        panelAsientosLayout.setVerticalGroup(
            panelAsientosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 244, Short.MAX_VALUE)
        );

        lbPantalla.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        lbPantalla.setText("PANTALLA");

        btnSelectFuncion.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        btnSelectFuncion.setText("SELECCIONAR FUNCIÓN");

        lbSala.setFont(new java.awt.Font("Roboto", 1, 24)); // NOI18N
        lbSala.setText("NOMBRE SALA");

        btnFactura.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        btnFactura.setText("FACTURA");

        lbFuncion.setFont(new java.awt.Font("Roboto", 1, 24)); // NOI18N
        lbFuncion.setText("NOMBRE FUNCIÓN");

        lbPrecio.setFont(new java.awt.Font("Roboto", 1, 24)); // NOI18N
        lbPrecio.setText("PRECIO BOLETO");

        lbHorario.setFont(new java.awt.Font("Roboto", 1, 24)); // NOI18N
        lbHorario.setText("HORARIO:");

        lbTotal.setFont(new java.awt.Font("Roboto", 1, 24)); // NOI18N
        lbTotal.setText("TOTAL $");

        javax.swing.GroupLayout fondoLayout = new javax.swing.GroupLayout(fondo);
        fondo.setLayout(fondoLayout);
        fondoLayout.setHorizontalGroup(
            fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, fondoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbHorario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(465, 465, 465)
                .addComponent(lblTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(fondoLayout.createSequentialGroup()
                .addGap(144, 144, 144)
                .addComponent(panelAsientos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(144, 144, 144))
            .addGroup(fondoLayout.createSequentialGroup()
                .addGap(486, 486, 486)
                .addComponent(lbPantalla, javax.swing.GroupLayout.DEFAULT_SIZE, 106, Short.MAX_VALUE)
                .addGap(471, 471, 471))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, fondoLayout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(fondoLayout.createSequentialGroup()
                        .addGroup(fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnSelectFuncion)
                            .addComponent(lbFuncion, javax.swing.GroupLayout.PREFERRED_SIZE, 433, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 299, Short.MAX_VALUE))
                    .addGroup(fondoLayout.createSequentialGroup()
                        .addComponent(btnFactura)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lbPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, 364, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40)))
                .addGroup(fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbSala, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        fondoLayout.setVerticalGroup(
            fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fondoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbHorario, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbFuncion, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbSala))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(fondoLayout.createSequentialGroup()
                        .addComponent(btnSelectFuncion)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnFactura))
                    .addGroup(fondoLayout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addGroup(fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(53, 53, 53)
                .addComponent(lbPantalla, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelAsientos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(44, 44, 44))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(fondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(fondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

private void crearEfectoPantalla(int ancho, int alto) {
    lbPantalla.setPreferredSize(new java.awt.Dimension(ancho, alto));
    lbPantalla.setSize(ancho, alto);
    lbPantalla.setText(""); // Borramos el texto

    // Aqui crea la imagen.
    BufferedImage img = new BufferedImage(ancho, alto, BufferedImage.TYPE_INT_ARGB);
    Graphics2D g2 = img.createGraphics();
    
    g2.setRenderingHint(RenderingHints.KEY_ANTIALIASING, RenderingHints.VALUE_ANTIALIAS_ON);

    // Dibuja el trapecio.
    int margen = 40; // Más margen para acentuar la perspectiva 3D
    GeneralPath trapecio = new GeneralPath();
    trapecio.moveTo(margen, 0);           // Arriba Izq
    trapecio.lineTo(ancho - margen, 0);   // Arriba Der
    trapecio.lineTo(ancho, alto);         // Abajo Der
    trapecio.lineTo(0, alto);             // Abajo Izq
    trapecio.closePath();

    // Degradado (Efecto luz de cine).
    GradientPaint gradiente = new GradientPaint(
            ancho / 2, 0, new Color(220, 220, 255), // Arriba: Luz fuerte
            ancho / 2, alto, new Color(80, 80, 100) // Abajo: Oscuridad
    );
    
    g2.setPaint(gradiente);
    g2.fill(trapecio);

    // Borde azul neón suave.
    g2.setColor(new Color(0, 150, 255)); 
    g2.setStroke(new java.awt.BasicStroke(2));
    g2.draw(trapecio);

    // Texto "PANTALLA" centrado.
    g2.setColor(Color.WHITE);
    g2.setFont(new java.awt.Font("SansSerif", java.awt.Font.BOLD, 16));
    java.awt.FontMetrics fm = g2.getFontMetrics();
    int textX = (ancho - fm.stringWidth("PANTALLA")) / 2;
    int textY = (alto - fm.getHeight()) / 2 + fm.getAscent();
    g2.drawString("PANTALLA", textX, textY);

    g2.dispose();
    
    // Asigna el icono.
    lbPantalla.setIcon(new ImageIcon(img));
 
    lbPantalla.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnFactura;
    public javax.swing.JButton btnSelectFuncion;
    private javax.swing.JPanel fondo;
    private javax.swing.JSeparator jSeparator1;
    public javax.swing.JLabel lbFuncion;
    public javax.swing.JLabel lbHorario;
    public javax.swing.JLabel lbPantalla;
    public javax.swing.JLabel lbPrecio;
    public javax.swing.JLabel lbSala;
    public javax.swing.JLabel lbTotal;
    private javax.swing.JLabel lblTitulo;
    public javax.swing.JPanel panelAsientos;
    // End of variables declaration//GEN-END:variables
}
